### ISSUE TITLE
[3.0.2]When verifying token, java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.JsonNode.asText(Ljava/lang/String;)Ljava/lang/String;

### ISSUE THREAD

**Issue by ziyaozou** [auth0/java-jwt#126]
I tried to learn how to use jwt with auth0's library, and my code is below:
```java
public class JWTTest {

    @Test
    public void test() {
        String token = null;
        try {
            long now = System.currentTimeMillis();
            token = JWT.create()
                    .withClaim("uid","123")
                    .withClaim("mob","123")
                    .withExpiresAt( new Date( now + 7200 ))
                    .sign(Algorithm.HMAC256("secret"));
            System.out.print( token );


        } catch (Exception e) {
            e.printStackTrace();
        }

        try{
            JWTVerifier verifier = JWT.require(Algorithm.HMAC256("secret")).build(); //Reusable verifier instance
            DecodedJWT jwt = verifier.verify(token);
            System.out.print( "uid: " + jwt.getClaim("uid" ) );
            System.out.println( "mob: "+ jwt.getClaim( "mob") );
            System.out.println( "exp: " + jwt.getExpiresAt() + ", algorithm: " + jwt.getAlgorithm() );
        }catch ( Exception e ){
            e.printStackTrace();
        }
    }
}
```

then i got error at the line: `DecodedJWT jwt = verifier.verify( token )`. The exception is below(the first line of output is token):
```
eyJhbGciOiJIUzI1NiJ9.eyJ1aWQiOiIxMjMiLCJleHAiOjE0ODE4MDQ2NDIsIm1vYiI6IjEyMyJ9.67IX_XSDLH8apJAYryDUDOZWEQ5BSN74kxUKtz_4c44
java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.JsonNode.asText(Ljava/lang/String;)Ljava/lang/String;

	at com.auth0.jwt.impl.HeaderDeserializer.getString(HeaderDeserializer.java:43)
	at com.auth0.jwt.impl.HeaderDeserializer.deserialize(HeaderDeserializer.java:31)
	at com.auth0.jwt.impl.HeaderDeserializer.deserialize(HeaderDeserializer.java:13)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2993)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2098)
	at com.auth0.jwt.impl.JWTParser.convertFromJSON(JWTParser.java:57)
	at com.auth0.jwt.impl.JWTParser.parseHeader(JWTParser.java:33)
	at com.auth0.jwt.JWTDecoder.parseToken(JWTDecoder.java:42)
	at com.auth0.jwt.JWTDecoder.<init>(JWTDecoder.java:28)
	at com.auth0.jwt.JWT.decode(JWT.java:24)
	at com.auth0.jwt.JWTVerifier.verify(JWTVerifier.java:241)
	at tes.dao.user.JWTTest.test(JWTTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

```

**Comment by lbalmaceda** [comment]
Hi @ziyaozou,
I created a new java project and copy-pasted your code into a psvm and it is working. Output:

```
eyJhbGciOiJIUzI1NiJ9.eyJ1aWQiOiIxMjMiLCJtb2IiOiIxMjMiLCJleHAiOjE0ODE4MzI2MzZ9.yGWpp7PsAU9WWU_ut2AeAx5xZvb6-JtmHClVSnr4y7Iuid: com.auth0.jwt.impl.JsonNodeClaim@dbd940dmob: com.auth0.jwt.impl.JsonNodeClaim@71d15f18
exp: Thu Dec 15 17:10:36 ART 2016, algorithm: HS256

Process finished with exit code 0
```

This seems to be more a jackson issue than a java-jwt one. We're currently using only the `com.fasterxml.jackson.core:jackson-databind:2.8.4` dependency. If your app uses other jackson dependencies, check that all of them have the same version. 

Cheers.

**Comment by ziyaozou** [comment]
@lbalmaceda Thanks for your reply ! i change the version of jackson, and i works.

hope that there could be some specification about the dependency of other jars.

Thanks a lot!

**Comment by lmiguelmh** [comment]
This problem occurs when deploying in Weblogic 12.2.1. WL loads an old version of this library from `oracle_common\modules`. Not even using [`prefer-application-packages` in `weblogic.xml`](https://docs.oracle.com/cd/E24329_01/web.1211/e21049/weblogic_xml.htm#WBAPP660) solves the problem. Be warned if you are going to use this library and deploy it in a WebLogic server!
