### ISSUE TITLE
 No static method decodeBase64

### ISSUE THREAD

**Issue by Kolyall** [auth0/java-jwt#185]
I'm trying to run the lib on Android
My code:
 ```
String token =
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1OTUzNjFjNDU0NGU2NDYxOTMxYWY1MzMiLCJhY2Nlc3MiOiJhdXRoIiwiaWF0IjoxNDk4NjQwNDA0fQ.dHlPdvq8-0h8SJeSZjVcJcW1WOW72HAL4oAb_cpzpsk"
 DecodedJWT jwt = JWT.decode(token);
 ```
Error:
```
Caused by: java.lang.NoSuchMethodError: No static method decodeBase64(Ljava/lang/String;)[B in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.boot.jar)
                                                                            at com.auth0.jwt.JWTDecoder.<init>(JWTDecoder.java:32)
                                                                            at com.auth0.jwt.JWT.decode(JWT.java:21)
```

**Comment by lbalmaceda** [comment]
Apache commons [decodeBase64](https://commons.apache.org/proper/commons-codec/apidocs/org/apache/commons/codec/binary/Base64.html#decodeBase64(java.lang.String)) isn't prepared for Android. The 3rd line of the [Readme](https://github.com/auth0/java-jwt) points Android users here -> https://github.com/auth0/JWTDecode.Android
