### ISSUE TITLE
No static method encodeBase64URLSafeString

### ISSUE THREAD

**Issue by gentlyj** [auth0/java-jwt#265]
java.lang.NoSuchMethodError: No static method encodeBase64URLSafeString([B)Ljava/lang/String; in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.boot.jar)
        at com.auth0.jwt.JWTCreator.sign(JWTCreator.java:330)
        at com.auth0.jwt.JWTCreator.access$100(JWTCreator.java:24)
        at com.auth0.jwt.JWTCreator$Builder.sign(JWTCreator.java:311)

 I used this library in android, and caused this error. I searched it, seems android need use their own Base64 class. Is there some way could solve this, or another library for android?

**Comment by gentlyj** [comment]
ok, I found [this library](https://github.com/jwtk/jjwt) is available in android.
