### ISSUE TITLE
Cannot use with uk.co.panaxiom:play-jongo:2.1.0-jongo1.3

### ISSUE THREAD

**Issue by yehancha** [auth0/java-jwt#335]
I'm trying to use ```"com.auth0" % "java-jwt" % "3.8.0"``` in a Play Framework application. It is working perfectly but when I add this, ```"uk.co.panaxiom" %% "play-jongo" % "2.1.0-jongo1.3"``` crashes.

I have added the packages in application.conf as:
```
libraryDependencies += "uk.co.panaxiom" %% "play-jongo" % "2.1.0-jongo1.3"
libraryDependencies += "com.auth0" % "java-jwt" % "3.8.0"
```
And after that when I try to insert a mongo object, it gives me:
```
Uncaught error from thread [application-akka.actor.default-dispatcher-8]: com.fasterxml.jackson.databind.introspect.AnnotatedMember.fixAccess()V, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.introspect.AnnotatedMember.fixAccess()V
	at org.jongo.marshall.jackson.JacksonObjectIdUpdater.mustGenerateObjectId(JacksonObjectIdUpdater.java:48)
	at org.jongo.Insert.preparePojo(Insert.java:72)
	at org.jongo.Insert.save(Insert.java:47)
	at org.jongo.MongoCollection.save(MongoCollection.java:128)
	at models.Beer.insert(Beer.java:22)
	at controllers.BeerController.add(BeerController.java:16)
	at router.Routes$$anonfun$routes$1.$anonfun$applyOrElse$8(Routes.scala:195)
	at play.core.routing.HandlerInvokerFactory$$anon$6.resultCall(HandlerInvoker.scala:142)
	at play.core.routing.HandlerInvokerFactory$$anon$6.resultCall(HandlerInvoker.scala:141)
	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$3$$anon$4$$anon$5.invocation(HandlerInvoker.scala:115)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:111)
	at play.http.DefaultActionCreator$1.call(DefaultActionCreator.java:32)
	at play.core.j.JavaAction.$anonfun$apply$8(JavaAction.scala:170)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:658)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:64)
	at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:71)
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:56)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete(Promise.scala:372)
	at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete$(Promise.scala:371)
	at scala.concurrent.impl.Promise$KeptPromise$Successful.onComplete(Promise.scala:379)
	at scala.concurrent.impl.Promise.transform(Promise.scala:33)
	at scala.concurrent.impl.Promise.transform$(Promise.scala:31)
	at scala.concurrent.impl.Promise$KeptPromise$Successful.transform(Promise.scala:379)
	at scala.concurrent.Future.map(Future.scala:292)
	at scala.concurrent.Future.map$(Future.scala:292)
	at scala.concurrent.impl.Promise$KeptPromise$Successful.map(Promise.scala:379)
	at scala.concurrent.Future$.apply(Future.scala:658)
	at play.core.j.JavaAction.apply(JavaAction.scala:171)
	at play.api.mvc.Action.$anonfun$apply$2(Action.scala:97)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[error] a.a.ActorSystemImpl - Uncaught error from thread [application-akka.actor.default-dispatcher-8]: com.fasterxml.jackson.databind.introspect.AnnotatedMember.fixAccess()V, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.introspect.AnnotatedMember.fixAccess()V
	at org.jongo.marshall.jackson.JacksonObjectIdUpdater.mustGenerateObjectId(JacksonObjectIdUpdater.java:48)
	at org.jongo.Insert.preparePojo(Insert.java:72)
	at org.jongo.Insert.save(Insert.java:47)
	at org.jongo.MongoCollection.save(MongoCollection.java:128)
	at models.Beer.insert(Beer.java:22)
	at controllers.BeerController.add(BeerController.java:16)
	at router.Routes$$anonfun$routes$1.$anonfun$applyOrElse$8(Routes.scala:195)
	at play.core.routing.HandlerInvokerFactory$$anon$6.resultCall(HandlerInvoker.scala:142)
	at play.core.routing.HandlerInvokerFactory$$anon$6.resultCall(HandlerInvoker.scala:141)
	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$3$$anon$4$$anon$5.invocation(HandlerInvoker.scala:115)
```
How can I add ```"com.auth0" % "java-jwt" % "3.8.0"``` without breaking ```"uk.co.panaxiom" %% "play-jongo" % "2.1.0-jongo1.3"```?

**Comment by lbalmaceda** [comment]
Sounds like this library and the one you're using require different versions of the `jackson` dependency. 

```
java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.introspect.AnnotatedMember.fixAccess()V
```

You'll need to search the way to pin that transitive dependency (jackson) to the right version, as it seems your dependencies manager is resolving the same version for the 2 dependencies and failing when one requires a method not existing in the jacons version that was resolved. 

In gradle one would run `gradle dependencies` to see the tree of dependencies and see which one is getting picked, and choose the right one later using a command like the one explained [here](https://docs.gradle.org/current/userguide/managing_transitive_dependencies.html#sec:enforcing_dependency_version)

**Comment by yehancha** [comment]
Thank you very much, @lbalmaceda . Going through your suggestion, I excluded `jackson` coming with `auth0` which fixed the issue.

`"com.auth0" % "java-jwt" % "3.8.0" exclude("com.fasterxml.jackson.core", "jackson-databind")`

**Comment by lbalmaceda** [comment]
Glad it helped 💯
