### ISSUE TITLE
ECDSAAlgorithm.DERToJOSE fails since 064a01

### ISSUE THREAD

**Issue by defnull** [auth0/java-jwt#348]
### Description

Signing a token with ES256 throws an `Invalid DER signature format` exception in `ECDSAAlgorithm.DERToJOSE` with keys that worked prior to 064a01eb.

### Environment

- Version of this library used: 3.8.1
- Version of Java framework used: 11

### Reproduction

Generate keys:
```[sh]
openssl ecparam -genkey -name secp521r1 -out ecdsa.pem
openssl ec -in ecdsa.pem -outform DER -out ecdsa_pub.der -pubout
openssl pkcs8 -topk8 -inform PEM -outform DER -in ecdsa.pem -out ecdsa_priv.der -nocrypt
```

Run the following code:
```[java]
public static void main(String[] args) throws Exception {
	final Path ecdsaPubFile = Paths.get("ecdsa_pub.der");
	final Path privFile = Paths.get("ecdsa_priv.der");
	final KeyFactory keyFactory = KeyFactory.getInstance("EC");
	final X509EncodedKeySpec pubSpec = new X509EncodedKeySpec(Files.readAllBytes(ecdsaPubFile));
	final PublicKey pubKey = keyFactory.generatePublic(pubSpec);
	final PKCS8EncodedKeySpec privSpec = new PKCS8EncodedKeySpec(Files.readAllBytes(privFile));
	final PrivateKey privKey = keyFactory.generatePrivate(privSpec);
	final Algorithm ES256 = Algorithm.ECDSA256((ECPublicKey) pubKey, (ECPrivateKey) privKey);

	ES256.sign(new byte[] {}, new byte[] {});
}
```

The very last line (`ES256.sign()`) will throw:
```
Exception in thread "main" com.auth0.jwt.exceptions.SignatureGenerationException: The Token's Signature couldn't be generated when signing using the Algorithm: SHA256withECDSA
	at com.auth0.jwt.algorithms.ECDSAAlgorithm.sign(ECDSAAlgorithm.java:65)
	at ...Main.main(Main.java:28)
Caused by: java.security.SignatureException: Invalid DER signature format.
	at com.auth0.jwt.algorithms.ECDSAAlgorithm.DERToJOSE(ECDSAAlgorithm.java:118)
	at com.auth0.jwt.algorithms.ECDSAAlgorithm.sign(ECDSAAlgorithm.java:63)
	... 1 more
```

Any ideas?

**Comment by defnull** [comment]
Bug found (on my side). Switching from `secp521r1` to `secp256r1` produced keys that no longer triggered this exception. I used the wrong curve. The error message is still misleading or at least not very helpful and there might be room for improvement (error message or docs), so I'll keep this issue open.
