### ISSUE TITLE
Throw JWTDecodeException in JWTDecoder when Base64 decoding fails

### ISSUE THREAD

**Issue by pglizniewicz** [auth0/java-jwt#415]
In the `JWTDecoder` constructor you are catching a `NullPointerException` thrown by `StringUtils#newStringUtf8` and rethrow it as a JWTDecodeException. It would be consistent if you would also do this with `IllegalArgumentException` thrown by the Base64 decoder (thrown from Base64#validateCharacter), since this is a JWT decode exception.

Currently, the caller of `JWT.decode` has to check for these exceptions. It's often enough to omit the first character of the JWT to trigger this exception.

**Comment by lbalmaceda** [comment]
@pglizniewicz I cannot find in the Javadocs where the `IllegalArgumentException` is said to be thrown. The `Base64.decodeBase64` doesn't throw one apparently https://commons.apache.org/proper/commons-codec/apidocs/org/apache/commons/codec/binary/Base64.html#decodeBase64-java.lang.String-.

Where is this coming from?
Cheers

**Comment by pglizniewicz** [comment]
It's thrown from `org.apache.commons.codec.binary.Base64.validateCharacter` and it's even documented there, but it gets through other Commons Codec calls where it's not documented (it's an unchecked exception, so they don't have to be explicit about it). Just try:

```JWT.decode("eyJ0eXAiOiJKV1QiLCJhbGciOcorrupted.eyJ0ZXN0IjoxMjN9.sLtFC2rLAzN0-UJ13OLQX6ezNptAQzespaOGwCnpqk");```

and you will see where it is originating from.

**Comment by lbalmaceda** [comment]
I just tried
```java
JWT.decode("eyJ0eXAiOiJKV1QiLCJhbGciOcorrupted.eyJ0ZXN0IjoxMjN9.sLtFC2rLAzN0-UJ13OLQX6ezNptAQzespaOGwCnpqk");
```

and I got

```java
Stacktrace was: com.auth0.jwt.exceptions.JWTDecodeException: The string '{"typ":"JWT","alg"9�+��my' doesn't have a valid JSON format.
	at com.auth0.jwt.impl.JWTParser.decodeException(JWTParser.java:75)
	at com.auth0.jwt.impl.JWTParser.parseHeader(JWTParser.java:51)
	at com.auth0.jwt.JWTDecoder.<init>(JWTDecoder.java:43)
	at com.auth0.jwt.JWTDecoder.<init>(JWTDecoder.java:30)
	at com.auth0.jwt.JWT.decode(JWT.java:45)
	at com.auth0.jwt.JWTDecoderTest.shouldThrowIfTheContentIsNotProperlyEncoded(JWTDecoderTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)
```

A `JWTDecodeException` is what it would be expected in this case. I cannot reproduce what you're reporting. Using java version "1.8.0_152"

**Comment by martin-sean** [comment]
I'm experiencing the same behaviour as @pglizniewicz. It appears to be caused by a change in a private validateCharacter method in Apache Common Codec >=1.13. It now throws an IllegalArgumentException if the last character results in an invalid base64 value.

**Comment by pglizniewicz** [comment]
I can reproduce exactly what @martin-sean has written. Changing the dependency to commons-codec 1.12 shows a stacktrace similar to @lbalmaceda . With 1.13 and 1.14 the exception changed.

**Comment by lbalmaceda** [comment]
👍 thanks for those details. I'll take another look in the coming weeks.
